spring:
  main:
    show-banner: true
  data:
    mongodb:
      uri: mongodb://localhost:27017/MasterCache
  redis:
    host: localhost
    port: 6379
    min-idle: 5
    max-active: 200

server:
    port: 8888
    session-timeout: 5
    tomcat:
        uri-encoding: UTF-8
        max-threads: 200

